Updated to work with opensource.apple.com repository.
git-svn-id: https://svn.calendarserver.org/repository/calendarserver/CalendarServer/trunk@15 e27351fd-9f3e-4f54-a53b-843176b1656c

diff --git a/run b/run
--- a/run
+++ b/run
@@ -336,11 +336,18 @@ fi;
 # PyKerberos
 #
 
+svn_uri_base="$(svn info "${caldav}" | sed -n -e 's|/CalendarServer/trunk$||' -e 's|^URL: ||p')";
+
+if [ -z "${svn_uri_base}" ]; then
+    echo "Unable to locate subversion base URI for sources.";
+    exit 1;
+fi;
+
 if ! py_have_module kerberos; then
   kerberos="${top}/PyKerberos";
 
   if ! "${disable_setup}"; then
-    svn_get "PyKerberos" "${kerberos}" "http://macosxserver.apple.com:8000/svn/PyKerberos/trunk" 3766;
+    svn_get "PyKerberos" "${kerberos}" "${svn_uri_base}/PyKerberos/trunk" 14;
 
     if "${force_setup}" || [ ! -d "${kerberos}/build/${py_platform_libdir}" ]; then
       echo "";
@@ -362,7 +369,7 @@ if ! py_have_module opendirectory; then
   opendirectory="${top}/PyOpenDirectory";
 
   if ! "${disable_setup}"; then
-    svn_get "PyOpenDirectory" "${opendirectory}" "http://macosxserver.apple.com:8000/svn/PyOpenDirectory/trunk" 3766;
+    svn_get "PyOpenDirectory" "${opendirectory}" "${svn_uri_base}/PyOpenDirectory/trunk" 14;
 
     if "${force_setup}" || [ ! -d "${opendirectory}/build/${py_platform_libdir}" ]; then
       echo "";
