Print a useful message when we can't find the config file.
git-svn-id: https://svn.calendarserver.org/repository/calendarserver/CalendarServer/branches/users/wsanchez/provisioning-2@602 e27351fd-9f3e-4f54-a53b-843176b1656c

diff --git a/run b/run
--- a/run
+++ b/run
@@ -161,6 +161,12 @@ run () {
   fi;
 
   if ! "${setup_only}"; then
+    if [ ! -f "${config}" ]; then
+        echo "Missing config file: ${config}";
+        echo "You might want to copy conf/caldavd-test.plist to conf/caldavd-dev.plist and start from there.";
+        exit 1;
+    fi;
+
     cd "${wd}";
     exec "${python}" "${caldav}/bin/caldavd" ${daemonize} \
         -f "${config}"                                    \
