Use logs dir for ./run.
git-svn-id: https://svn.calendarserver.org/repository/calendarserver/CalendarServer/trunk@864 e27351fd-9f3e-4f54-a53b-843176b1656c

diff --git a/run b/run
--- a/run
+++ b/run
@@ -172,13 +172,16 @@ run () {
 
   if ! "${setup_only}"; then
     if [ ! -f "${config}" ]; then
-        echo "Missing config file: ${config}";
-        echo "You might want to start by copying the test configuration:";
-        echo "  cp conf/caldavd-test.plist conf/caldavd-dev.plist";
-        exit 1;
+      echo "Missing config file: ${config}";
+      echo "You might want to start by copying the test configuration:";
+      echo "  cp conf/caldavd-test.plist conf/caldavd-dev.plist";
+      exit 1;
     fi;
 
     cd "${wd}";
+    if [ ! -d "${wd}/logs" ]; then
+      mkdir "${wd}/logs";
+    fi;
     exec /bin/sh "${caldav}/bin/caldavd" ${daemonize} \
         -f "${config}"                                \
         -T "${twisted}/bin/twistd"                    \
